# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='raw_metadata.proto',
  package='evarilos',
  serialized_pb='\n\x12raw_metadata.proto\x12\x08\x65varilos\"\x84\x03\n\x08Metadata\x12\x0f\n\x07\x64\x61ta_id\x18\x01 \x02(\t\x12\x13\n\x0bmetadata_id\x18\x02 \x02(\t\x12\x15\n\rtimestamp_utc\x18\x03 \x02(\x03\x12\x12\n\ntestbed_id\x18\x04 \x02(\t\x12\x39\n\x08scenario\x18\x05 \x02(\x0b\x32\'.evarilos.Metadata.Scenario_description\x12\x0f\n\x07licence\x18\x06 \x02(\t\x12\x0b\n\x03_id\x18\x07 \x01(\x0c\x1a\xcd\x01\n\x14Scenario_description\x12\x1c\n\x14receiver_description\x18\x01 \x02(\t\x12\x1a\n\x12sender_description\x18\x02 \x02(\t\x12\x1f\n\x17\x65nvironment_description\x18\x03 \x02(\t\x12\x1e\n\x16\x65xperiment_description\x18\x04 \x02(\t\x12\x18\n\x10type_of_raw_data\x18\x05 \x02(\t\x12 \n\x18interference_description\x18\x06 \x01(\t')




_METADATA_SCENARIO_DESCRIPTION = descriptor.Descriptor(
  name='Scenario_description',
  full_name='evarilos.Metadata.Scenario_description',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='receiver_description', full_name='evarilos.Metadata.Scenario_description.receiver_description', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sender_description', full_name='evarilos.Metadata.Scenario_description.sender_description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='environment_description', full_name='evarilos.Metadata.Scenario_description.environment_description', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='experiment_description', full_name='evarilos.Metadata.Scenario_description.experiment_description', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type_of_raw_data', full_name='evarilos.Metadata.Scenario_description.type_of_raw_data', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='interference_description', full_name='evarilos.Metadata.Scenario_description.interference_description', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=216,
  serialized_end=421,
)

_METADATA = descriptor.Descriptor(
  name='Metadata',
  full_name='evarilos.Metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='data_id', full_name='evarilos.Metadata.data_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='metadata_id', full_name='evarilos.Metadata.metadata_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp_utc', full_name='evarilos.Metadata.timestamp_utc', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='testbed_id', full_name='evarilos.Metadata.testbed_id', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='scenario', full_name='evarilos.Metadata.scenario', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='licence', full_name='evarilos.Metadata.licence', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='_id', full_name='evarilos.Metadata._id', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_METADATA_SCENARIO_DESCRIPTION, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=421,
)

_METADATA_SCENARIO_DESCRIPTION.containing_type = _METADATA;
_METADATA.fields_by_name['scenario'].message_type = _METADATA_SCENARIO_DESCRIPTION
DESCRIPTOR.message_types_by_name['Metadata'] = _METADATA

class Metadata(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Scenario_description(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _METADATA_SCENARIO_DESCRIPTION
    
    # @@protoc_insertion_point(class_scope:evarilos.Metadata.Scenario_description)
  DESCRIPTOR = _METADATA
  
  # @@protoc_insertion_point(class_scope:evarilos.Metadata)

# @@protoc_insertion_point(module_scope)
